version: '3.7'

services:
  indexer:
    container_name: indexer
    image: indexer
    volumes:
      - ./.data:/var/app/.data
    ports:
      - "9096:9096"
    command: ${CMD}
      
  api-docs:
    container_name: indexer-api
    image: quay.io/goswagger/swagger
    volumes:
      - ./:/app
    ports:
      - "8080:12333"
    command: serve /app/swagger.yml --port 12333 --no-open