swagger: "2.0"
info:
  title: "Tx-indexer API"
  version: 0.0.1
  description: "Tx-indexer is a modular blockchain transaction monitoring tool. the app can monitor send/receive tx for a specific address over a specific period, multiple coins are supported and unified in a common tx format. repo: https://github.com/SwingbyProtocol/tx-indexer"
  termsOfService: "https://docs.swingby.network/terms.pdf"
  contact:
    name: "Support"
    email: "support@swingby.network"
  license:
    name: "AGPL 3.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
schemes:
  - https
produces:
  - application/json

tagsSorter: "method"

paths:
  /api/v1/status:
    get:
      summary: Get API Status
      description: Get API state
      operationId: getStatus
      produces:
        - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/ResultStatus"

  /api/v1/bnb/memo_txs:
    get:
      summary: Get transactions which includes a memo
      description: Get transactions on the Binance chain.
      operationId: getSetTxs
      produces:
        - application/json
      parameters:
        - name: memo
          in: query
          required: true
          type: integer
          description: A param that specifies the memo text
        - name: page
          in: query
          required: false
          type: integer
          description: A param that specifies the page number (default=1)
        - name: limit
          in: query
          required: false
          type: integer
          description: A param that specifies the number of tx to be acquired per page (default=25)
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/Tx"

  /api/v1/bnb/self:
    get:
      summary: Get Self-send transactions
      description: Get Self-send transactions on the Binance chain.
      operationId: getSelfTxs
      produces:
        - application/json
      parameters:
        - name: page
          in: query
          required: false
          type: integer
          description: A param that specifies the page number (default=1)
        - name: limit
          in: query
          required: false
          type: integer
          description: A param that specifies the number of tx to be acquired per page (default=25)
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/Tx"

  /api/v1/{currency}/txs:
    get:
      summary: Get transaction
      description: Get transactions (input/output)
      operationId: getTxs
      produces:
        - application/json
      parameters:
        - name: currency
          in: path
          required: false
          type: string
          description: Target currency e.g. "bnb", "eth", "btc"
        - name: watch
          in: query
          required: true
          type: string
          description: Target address to watch in/out txs
        - name: height_from
          in: query
          required: false
          type: integer
          description: A param that specifies the start height. e.g. 1812922 (default=0)
        - name: height_to
          in: query
          required: false
          type: integer
          description: A param that specifies the end height. e.g. 1822922 (default=0)(latest)
        - name: page
          in: query
          required: false
          type: integer
          description: A param that specifies the page number (default=1)
        - name: limit
          in: query
          required: false
          type: integer
          description: A param that specifies the number of tx to be acquired per page (default=25)
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/ResultGetTxs"
  

definitions:
  ResultStatus:
    type: object
    properties:
      result:
        type: boolean
        title: result
        example: true
  ResultGetTxs:
    type: object
    properties:
      result:
        type: boolean
        example: true
      latestHeight:
        type: integer
        example: 1772112
      inTxsMempool:
        type: array
        items:
          $ref: "#/definitions/Tx"
      inTxs:
        type: array
        items:
          $ref: "#/definitions/Tx"
      outTxsMempool:
        type: array
        items:
          $ref: "#/definitions/Tx"
      outTx:
        type: array
        items:
          $ref: "#/definitions/Tx"
  ResultRescan:
    type: object
    properties:
      result:
        type: boolean
        example: false
      msg:
        type: string
        example: "re-scanning"
  ResultSuccessConfig:
    type: object
    properties:
      result:
        type: boolean
        example: true
      msg:
        type: string
        example: "success"
  ResultErrorConfig:
    type: object
    properties:
      result:
        type: boolean
        example: false
      msg:
        type: string
        example: "<Error message()>"
  Tx:
    properties:
      txId:
        type: string
        title: TxId
        example: 1F842B199B790317A392420EDDBFE6EFAECB5A8A1A71A950EDA572E94804A6C0
      from:
        type: string
        title: From
        example: bnb1pqx2c3fr5vh7fuc6pthucuujpcxphnsn5ac3ge
      to:
        type: string
        title: To
        example: bnb1pqx2c3fr5vh7fuc6pthucuujpcxphnsn5ac3ge
      amount:
        type: string
        title: Amount
        example: "1000000"
      currency:
        type: string
        title: Currency
        example: BNB
      decimals:
        type: integer
        title: Decimals
        example: 8
      time:
        type: integer
        title: Timestamp (unix)
        example: 1577488326
      memo:
        type: string
        title: Memo
        example: ""
      outputIndex:
        type: integer
        title: OutputIndex
        example: 0
      spent:
        type: boolean
        title: Spent
        example: false
